// JavaScript Document
$(function(){
		//显示隐藏下拉框
		//系统菜单
		$("#erXitongC").click(function(){
			$("#xitongC").toggle("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//商品管理
		$("#erShangpin").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").toggle("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//交易管理
		$("#erJiaoyi").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").toggle("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//促销管理
		$("#erCuxiao").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").toggle("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//会员管理
		$("#erHuiyuan").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").toggle("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//商家管理
		$("#erShangjia").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").toggle("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//PC端首页管理
		$("#erShouye").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").toggle("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//运营管理
		$("#erYunying").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").toggle("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//统计结算
		$("#erTongji").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").toggle("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//搜索管理
		$("#erSousuo").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").toggle("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//系统管理
		$("#erXitongG").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").toggle("slow");
			$("#wangzhan").slideUp("slow");
		})
		
		//网站文章
		$("#erWangzhan").click(function(){
			$("#xitongC").slideUp("slow");
			$("#shangpin").slideUp("slow");
			$("#jiaoyi").slideUp("slow");
			$("#cuxiao").slideUp("slow");
			$("#huiyuan").slideUp("slow");
			$("#shangjia").slideUp("slow");
			$("#shouye").slideUp("slow");
			$("#yunying").slideUp("slow");
			$("#tongji").slideUp("slow");
			$("#sousuo").slideUp("slow");
			$("#xitongG").slideUp("slow");
			$("#wangzhan").toggle("slow");
		})
		
	});